import type { SettingCatalog, SettingInfo } from '@comparer/core';
import generated from '../data/settings.json' with { type: 'json' };

/** One entry of data/settings.json, generated by tools/extract-settings. */
export interface CatalogEntry {
  readonly label?: string;
  readonly fullLabel?: string;
  readonly category?: string;
  readonly tooltip?: string;
  readonly unit?: string;
}

export function createSettingCatalog(
  entries: Readonly<Record<string, CatalogEntry>> = generated.settings,
): SettingCatalog {
  return {
    describe(key) {
      const entry = entries[key];
      if (!entry) return undefined;
      // OrcaSlicer's short labels ("Other layers") lean on their tab context; prefer full_label.
      const info: SettingInfo = {
        key,
        label: entry.fullLabel ?? entry.label ?? key,
        ...(entry.category ? { group: entry.category } : {}),
        ...(entry.tooltip ? { tooltip: entry.tooltip } : {}),
        ...(entry.unit ? { unit: entry.unit } : {}),
      };
      return info;
    },
  };
}
