import type {
  LegacyKeys,
  ProfileType,
  RawValue,
  SettingCatalog,
  SettingInfo,
} from '@comparer/core';
import generated from '../data/settings.json' with { type: 'json' };

/** One entry of data/settings.json, generated by tools/extract-settings. */
export interface CatalogEntry {
  readonly label?: string;
  readonly fullLabel?: string;
  readonly category?: string;
  readonly tooltip?: string;
  readonly unit?: string;
  /** The built-in default, as OrcaSlicer writes it to a profile file. */
  readonly default?: RawValue;
}

/** The shape of data/settings.json. */
export interface CatalogData {
  /** The settings each preset type owns (OrcaSlicer's Preset.cpp option lists). */
  readonly presetTypes: Readonly<Partial<Record<ProfileType, readonly string[]>>>;
  readonly settings: Readonly<Record<string, CatalogEntry>>;
  /** OrcaSlicer's handle_legacy: keys it discards, and old keys it renames. */
  readonly legacy?: {
    readonly obsolete: readonly string[];
    readonly renamed: Readonly<Record<string, string>>;
  };
}

export function createSettingCatalog(data: CatalogData = generated): SettingCatalog {
  const defaultsByType = new Map<ProfileType, ReadonlyMap<string, RawValue>>();
  const legacyKeys: LegacyKeys = {
    obsolete: new Set(data.legacy?.obsolete),
    renamed: new Map(Object.entries(data.legacy?.renamed ?? {})),
  };

  return {
    describe(key) {
      const entry = data.settings[key];
      if (!entry) return undefined;
      // OrcaSlicer's short labels ("Other layers") lean on their tab context; prefer full_label.
      const info: SettingInfo = {
        key,
        label: entry.fullLabel ?? entry.label ?? key,
        ...(entry.category ? { group: entry.category } : {}),
        ...(entry.tooltip ? { tooltip: entry.tooltip } : {}),
        ...(entry.unit ? { unit: entry.unit } : {}),
      };
      return info;
    },

    defaultsFor(type) {
      let defaults = defaultsByType.get(type);
      if (!defaults) {
        defaults = new Map(
          (data.presetTypes[type] ?? []).flatMap((key) => {
            const value = data.settings[key]?.default;
            return value === undefined ? [] : [[key, value] as const];
          }),
        );
        defaultsByType.set(type, defaults);
      }
      return defaults;
    },

    legacyKeys: () => legacyKeys,
  };
}
